version: "3.1"

services:
  appcentdemoweb:
    image: cihangiremir/appcentdemo:first
    ports:
      - "5001:5001"
  couchbasedb:
    image: couchbase:latest
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"